# Generated by Django 3.1.3 on 2020-12-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_food_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flights',
            new_name='flight',
        ),
    ]
