# Generated by Django 3.1.3 on 2020-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20201204_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='meal', to='flights.Flight'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='food_choice',
            field=models.ManyToManyField(blank=True, related_name='food_choice', to='flights.Food'),
        ),
    ]
